sudo: required
language: node_js
node_js:
  - node
before_script:
  - npm install -g npm
  - npm install -g jsdoc documentation
script:
  - npm run doc
deploy:
  provider: pages
  local-dir: docs
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  on:
    branch: master